version: '3.9'
services:

  server:
    build: .
    environment:
      - DATABASE_DSN=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - 8080

  db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "-h", "redis", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
