name: CI
on:
  push:
    branches:
      - main

env:
  GO_VERSION: 1.18

jobs:

  mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: |
          go mod tidy
          git diff --exit-code go.mod

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - name: Build
        run: |
          go build -v ./...
      - name: Run Tests
        run: |
          go test -v ./...
