name: CI
on:
  push:
    branches:
      - main

jobs:
  go_mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: |
          go mod tidy
          git diff --exit-code go.mod
