name: CI
on:
  push:
    branches:
      - main

env:
  GO_VERSION: 1.18

jobs:
  go_mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: |
          go mod tidy
          git diff --exit-code go.mod
